spring:
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ncov-ph-do-user-2946816-0.a.db.ondigitalocean.com:25060/account
    username: doadmin
    password: bziz8bp7uz1uh56u

    ##    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    ##  username: ${POSTGRES_USER}
    ##  password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://ncov-ph-do-user-2946816-0.a.db.ondigitalocean.com:25060/account
    ##  url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    schemas: account
    connectRetries: 10
    installed-by: mtagab
    locations: classpath:db/migration
    validate-on-migrate: true
  profiles:
    active: kubernetes
server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway,refresh,keepalive
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
