create table credentials (
    userId             bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           varchar(255)    NOT NULL,
    password           varchar(255)    NOT NULL,
    accountType        varchar(255)    NOT NULL,
    rolesId            int             NOT NULL,
    isActivated        boolean         NOT NULL,
    registeredOn       date            DEFAULT  CURRENT_DATE NOT NULL,
    status             varchar(255)    NOT NULL
);

create unique index credentials_index on credentials (username);
