apiVersion: certmanager.k8s./v1alpha1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'proxyshadow@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
