spring:
  profiles:
    active: kubernetes
---
spring:
  application:
    name: authentication
  profiles: development
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false
        enabled: false
      config:
        enabled: false
  flyway:
    enabled: false
server:
  servlet:
    context-path: /
    session:
      cookie:
        name: OAUTH2SESSION
  port: 7070
  error:
    include-stacktrace: on_trace_param

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoint:
    health:
      enabled: false
    beans:
      enabled: false
    info:
      enabled: false
    shutdown:
      enabled: false
    flyway:
      enabled: false
---
spring:
  application:
    name: authentication
  profiles: kubernetes
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
      config:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    schemas: authentication
    connectRetries: 10
    installed-by: mtagab
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  servlet:
    context-path: /
    session:
      cookie:
        name: OAUTH2SESSION
  port: 7070
  error:
    include-stacktrace: on_trace_param

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway,refresh,keepalive
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    restart:
      enabled: true
    beans:
      enabled: true
    flyway:
      enabled: true
eureka:
  client:
    enabled: false
