apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: mtagab/account
      context: account
      docker:
        dockerfile: Dockerfile
    - image: mtagab/government
      context: government
      docker:
        dockerfile: Dockerfile
    - image: mtagab/hospital
      context: hospital
      docker:
        dockerfile: Dockerfile
    - image: mtagab/infection
      context: infection
      docker:
        dockerfile: Dockerfile
    - image: mtagab/notification
      context: notification
      docker:
        dockerfile: Dockerfile
    - image: mtagab/person
      context: person
      docker:
        dockerfile: Dockerfile
    - image: mtagab/authentication
      context: security/authentication
      docker:
        dockerfile: Dockerfile
    - image: mtagab/resource
      context: security/resource
      docker:
        dockerfile: Dockerfile
    - image: mtagab/skeleton
      context: skeleton
      docker:
        dockerfile: Dockerfile
  tagPolicy:
      sha256: {}
  local: {}

deploy:
  kubectl:
    manifests:
      - deploy.yaml

