spring:
  profiles:
    active: kubernetes
---
spring:
  application:
    name: skeleton
  profiles: development
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: healthtracker
            client-secret: dWzCGD4Zfx4Dg5p5
            scope: read,write,foo
            authorization-grant-type: authorization_code
            redirect-uri:  http://localhost/api/oath
        provider:
          custom:
            authorization-uri: http:/localhost:7070/authserver/oauth/authorize
            token-uri: http://localhost:7070/authserver/oauth/token
            user-info-uri: http://localhost:9000/resource/users/extra
            user-name-attribute: user_name
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    static-locations: classpath:/public/
    cache:
      period: 0s
    add-mappings: false

spa:
  default-file: classpath:/public/index.html

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: on_trace_param


management:
  endpoint:
    health:
      enabled: false
    beans:
      enabled: false
    info:
      enabled: false
    shutdown:
      enabled: false

---
spring:
  application:
    name: skeleton
  profiles: kubernetes
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: healthtracker
            client-secret: dWzCGD4Zfx4Dg5p5
            scope: read,write,foo
            authorization-grant-type: authorization_code
            redirect-uri:  http://viper.net/api/oath
        provider:
          custom:
            authorization-uri: http://${AUTHORIZATION_SERVER}:7070/authserver/oauth/authorize
            token-uri: http://${AUTHORIZATION_SERVER}:7070/authserver/oauth/token
            user-info-uri: http://${RESOURCE_SERVER}:9000/resource/users/extra
            user-name-attribute: user_name
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    static-locations: classpath:/public/
    cache:
      period: 0s
    add-mappings: false

spa:
  default-file: classpath:/public/index.html

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: on_trace_param

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      enabled: true
    info:
      enabled: true




