create table users (
    userId             bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           varchar(255)    NOT NULL,
    first_name         varchar(255)    NOT NULL,
    last_name          varchar(255)    NOT NULL,
    contact_no         varchar(255)    NOT NULL,
    email              varchar(255)    NOT NULL,
    address            varchar(255)    NOT NULL,
    nationality        varchar(255)    NOT NULL
);

create unique index user_index on users (username);
