create table photos (
    photoId          bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo            varchar(255)    NOT NULL,
    userId           int             NOT NULL,
    uploadedOn       date            DEFAULT CURRENT_DATE NOT NULL

);

create unique index photos_index on photos (userId);
