create table configuration
(
    configId    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configName  varchar(255) NOT NULL,
    configValue varchar(255) NOT NULL
);

create unique index configuration_index on configuration (configName);
