create table hospitals (
    hospitalId        bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospitalName      varchar(255)    NOT NULL,
    hospitalType      varchar(255)    NOT NULL,
    address           varchar(255)    NOT NULL
);

create unique index hospitals_index on hospitals (hospitalId);