create table laboratory (
    laboratoryId   bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    labName        varchar(255)     NOT NULL,
    labType        varchar(255)     NOT NULL,
    isOperational  boolean          DEFAULT TRUE NOT NULL,
    hospitalId     bigint           NOT NULL
);

create unique index laboratory_index on laboratory (labType);