create table monitoring (
    monitoringId    bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patientId       bigint          NOT NULL,
    hospitalId      bigint          NOT NULL,
    healthStatus    varchar(255)    DEFAULT '' NOT NULL,
    patientStatus   varchar(255)    DEFAULT '' NOT NULL,
    testResult      varchar(255)    DEFAULT '' NOT NULL,
    dateAdded       date            DEFAULT CURRENT_DATE NOT NULL,
    updatedOn       date            DEFAULT CURRENT_DATE NOT NULL
);

create unique index monitoring_index on monitoring (patientId);
