create table quarantine (
    quarantineId     bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patientId        bigint          NOT NULL,
    symptoms         varchar(255)    DEFAULT '' NOT NULL,
    status           varchar(255)    NOT NULL,
    isTested         boolean         NOT NULL,
    isInfected       boolean         NOT NULL,
    isAsymptomatic   boolean         NOT NULL,
    quarantineDate   date         DEFAULT CURRENT_DATE NOT NULL
);

create unique index quarantine_index on quarantine (patientId);
