create table request (
   requestId                bigint             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   requestName              varchar(255)       NOT NULL,
   description              varchar(500)       NOT NULL,
   requestStatus            varchar(255)       NOT NULL,
   requestedBy              bigint             NOT NULL,
   hospitalId               bigint             NOT NULL,
   isFulfilled              boolean            DEFAULT FALSE NOT NULL,
   requestDate              date               NOT NULL
);

create unique index request_index on request (requestName);