create table supplies (
   itemId       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   itemName     varchar(255)    NOT NULL,
   description  varchar(255)    DEFAULT  '' NOT NULL,
   quantity     int             NOT NULL,
   used         int             NOT NULL,
   remaining    int             NOT NULL,
   hospitalId   bigint          NOT NULL,
   datedAdded   date            DEFAULT CURRENT_DATE NOT NULL,
   updatedOn    date            DEFAULT CURRENT_DATE NOT NULL
);

create unique index supplies_index on supplies (itemName);
