create table workers (
    workerId     bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workerName   varchar(255)    NOT NULL,
    workRole     varchar(255)    NOT NULL,
    status       varchar(255)    NOT NULL,
    hospitalId   bigint          NOT NULL
);

create unique index workers_index on workers (hospitalId);
