server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: client
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: authserverD
            client-secret: authserverDPass
            scope: read,write,foo
            authorization-grant-type: authorization_code
            redirect-uri: http://viper/main
        provider:
          custom:
            authorization-uri: http://localhost:7070/authserver/oauth/authorize
            token-uri: http://localhost:7070/authserver/oauth/token
            user-info-uri: http://localhost:9000/resource/users/extra
            user-name-attribute: user_name
  thymeleaf:
    cache: false

logging:
  level:
    org.org.springframework: INFO
