apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthtracker
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  backend:
    serviceName: website
    servicePort: 8080
  rules:
    - host: mtagab.local
      http:
        paths:
          - path: /account(/|$)(.*)
            backend:
              serviceName: account
              servicePort: 8080
          - path: /government(/|$)(.*)
            backend:
              serviceName: government
              servicePort: 8080
          - path: /infection
            backend:
              serviceName: infection
              servicePort: 8080
          - path: /notification
            backend:
              serviceName: notification
              servicePort: 8080
          - path: /security
            backend:
              serviceName: security
              servicePort: 8080
          - path: /hospital
            backend:
              serviceName: hospital
              servicePort: 8080
          - path: /person(/|$)(.*)
            backend:
              serviceName: person
              servicePort: 8080
          - path: /gateway
            backend:
              serviceName: gateway
              servicePort: 8080
