spring:
  profiles:
    active: "kubernetes"
  main:
    banner-mode: "off"

---
spring:
  application:
    name: authentication
  profiles: dev

  flyway:
    enabled: true
    user: postgres
    password:
    url: jdbc:postgresql://localhohst:5432/postgres
    schemas: security
    connectRetries: 10
    installed-by: mtagab
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 7070
  servlet:
    context-path: /authserver
    session:
      cookie:
        name: OAUTH2SESSION
---
spring:
  application:
    name: authentication
  profiles: kubernetes
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    schemas: security
    connectRetries: 10
    installed-by: mtagab
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  servlet:
    context-path: /authserver
    session:
      cookie:
        name: OAUTH2SESSION
  port: 7070
  error:
    include-stacktrace: on_trace_param

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway,refresh,keepalive
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true