apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  selector:
    app: account
  ports:
    - name: account
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: government
  labels:
    app: government
spec:
  selector:
    app: government
  ports:
    - name: government
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - name: notification
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: security
  labels:
    app: security
spec:
  selector:
    app: security
  ports:
    - name: security
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: infection
  labels:
    app: infection
spec:
  selector:
    app: infection
  ports:
    - name: infection
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hospital
  labels:
    app: hospital
spec:
  selector:
    app: hospital
  ports:
    - name: hospital
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: person
  labels:
    app: person
spec:
  selector:
    app: person
  ports:
    - name: person
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
    - name: website
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
