server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: resource

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway,refresh,keepalive
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
