CREATE DATABASE account;
GRANT ALL PRIVILEGES ON DATABASE account TO mtagab;

CREATE DATABASE government;
GRANT ALL PRIVILEGES ON DATABASE government TO mtagab;

CREATE DATABASE hospital;
GRANT ALL PRIVILEGES ON DATABASE hospital TO mtagab;

CREATE DATABASE infection;
GRANT ALL PRIVILEGES ON DATABASE infection TO mtagab;

CREATE DATABASE notification;
GRANT ALL PRIVILEGES ON DATABASE notification TO mtagab;

CREATE DATABASE authentication;
GRANT ALL PRIVILEGES ON DATABASE authentication TO mtagab;

CREATE DATABASE resource;
GRANT ALL PRIVILEGES ON DATABASE resource TO mtagab;

CREATE DATABASE person;
GRANT ALL PRIVILEGES ON DATABASE person TO mtagab;
