create table travel (
    travelId       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId         bigint          NOT NULL,
    location       varchar(100)    NOT NULL,
    country        varchar(50)    NOT NULL,
    travelDate     date            DEFAULT CURRENT_DATE NOT NULL
);

create unique index travel_index on travel (userId);
