create table admission_instruction (
    instructionId       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId              bigint          NOT NULL,
    contactPerson       varchar(255)    NOT NULL,
    pickupLocation      varchar(255)    NOT NULL,
    status              varchar(255)    NOT NULL,
    validatedBy         bigint          NOT NULL,
    requestedOn         date            DEFAULT CURRENT_DATE NOT NULL,
    pickupDateTime      date            DEFAULT CURRENT_DATE NOT NULL
);

create unique index admission_index on admission_instruction (userId);
