create table code_alert (
    alertId             bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location            varchar(255)     NOT NULL,
    updatedBy           int              NOT NULL,
    alert_level         int              NOT NULL,
    isLocal             boolean          DEFAULT FALSE NOT NULL,
    updatedOn           date             DEFAULT CURRENT_DATE NOT NULL
);

create unique index code_alert_index on code_alert (alert_level);
