create table public_advisory (
    advisoryId     bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisory       varchar(800)    NOT NULL,
    createdBy      bigint          NOT NULL,
    createdOn      date            DEFAULT CURRENT_DATE NOT NULL,
    updatedOn      date            DEFAULT CURRENT_DATE NOT NULL
);

create unique index advisory_index on public_advisory (advisoryId);