create table travel_local_alert (
    travelId       bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_level    varchar(500)     NOT NULL,
    location       varchar(500)     NOT NULL,
    createdBy      bigint           NOT NULL,
    createdOn      date             DEFAULT CURRENT_DATE NOT NULL
);

create table travel_national_alert (
    travelId       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_level    varchar(500)    NOT NULL,
    location       varchar(500)    NOT NULL,
    createdBy      bigint          NOT NULL,
    createdOn      date            DEFAULT CURRENT_DATE NOT NULL
);


create unique index local_alert_index on travel_local_alert (alert_level);
create unique index national_alert_index on travel_national_alert (alert_level);
